language: node_js
node_js:
  - '0.10'
before_install:
  - npm install -g grunt-cli
  - git config user.email "build@travis-ci.com"
  - git config user.name "Travis CI"
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GH_TOKEN}:@github.com" > .git/credentials
  - git remote add publish https://github.com/VicNumber21/txtml.git
  - git fetch publish develop:develop
  - git checkout $TRAVIS_BRANCH
script: grunt publish
branches:
  except:
    - gh-pages
    - /^noci*$/i
env:
  global:
    secure: SomarYaaj5sHX4Nj0V7bBNDduxHuKE7c1TDtATmayUrm6XE7ALEQJeBXWWy73QzZCOy6Ur9MrJfl5//dpXHqNfvgWyAdbZjs6uMK94lu5O7+uKjDtTmsl/dGeNAE+C7IFoeE4YBRiByhn42wxPFTqDVuEtl+8Hf/Mfep1AdpE6k=
