language: node_js
node_js:
  - '0.10'
before_install:
  - npm install -g grunt-cli
  - git config user.email "build@travis-ci.com"
  - git config user.name "Travis CI"
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GH_TOKEN}:@github.com" > .git/credentials
  - git remote add publish https://github.com/VicNumber21/txtml.git
  - git fetch publish develop:develop
  - git checkout $TRAVIS_BRANCH
script: grunt publish
branches:
  except:
    - gh-pages
    - develop
    - master
    - /^noci*$/i
env:
  global:
    secure: Tv8NEIxSjZA8Jq4gt8NBRaSuNHQAXIbL8+QThqFBkZE+P9xPEHssTBF76U7tATZB2y6ouFwwVRMSShuIWNGCx2dcB0NS9LC5PeXoXsaWNVYEbkM9+9Wmq1QeabN4H2FhJoBR1FEP4dt2X00U0h4jh7w50geYDDfdoJ2Kg1w5ZKA=
